Nicolas' quit button
jnburchett/joebvp pull request #20
Opened 2017-12-14 01:13 UTC by jnburchett

As titled.  Also added patch in convolvecos for empty cfg.fitidx

2017-12-14 17:15 UTC, ntejos commented
Just tested it on my computer, and it breaks once pressed. It seems is not quitting properly...

2017-12-15 12:37 UTC, ntejos requested changes

2017-12-15 12:37 UTC, ntejos commented on joebvp/makevoigt.py
>              # import pdb; pdb.set_trace()
Are you sure this is what we want? i.e. for the case of empty `cfg.fitidx=[]`, `fitwaves` will become the full wavelength array...

2017-12-15 17:12 UTC, jnburchett commented on joebvp/makevoigt.py
>              # import pdb; pdb.set_trace()
Can you recommend something better?

2017-12-15 18:58 UTC, ntejos commented on joebvp/makevoigt.py
>              # import pdb; pdb.set_trace()
Nop, but not sure if this will be used at all. If you leave it with "pass" it may just work the same.

2017-12-15 19:04 UTC, ntejos approved these changes

2017-12-15 19:23 UTC, ntejos commented
I think I solved the problem now. Please review my latest commit.

2017-12-23 00:09 UTC, ntejos commented
@jnburchett are we good with this?

2017-12-26 15:27 UTC, jnburchett commented
The GUI now takes longer to load, which I suspect is due to one of my changes, but we have addressed the issues at hand.  Merging.

2017-12-26 15:27 UTC, merged